// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yndzwstirqaeigyjbhjm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InluZHp3c3RpcnFhZWlneWpiaGptIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0MDM1MjksImV4cCI6MjA2OTk3OTUyOX0.n2X8bTwCtvMEKqQZHCd--kdErlfU_hL2sppjljhc2Aw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});